source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

# MJApiClient dependencies
pod 'AFNetworking', '~> 3.0.4'
pod 'FormatterKit/URLRequestFormatter', '~>1.8.0'

# Removing unused localizations
pre_install do |installer|
    supported_locales = ['base', 'en']
    
    Dir.glob(File.join(installer.sandbox.pod_dir('FormatterKit'), '**', '*.lproj')).each do |bundle|
        if (!supported_locales.include?(File.basename(bundle, ".lproj").downcase))
            puts "Removing #{bundle}"
            FileUtils.rm_rf(bundle)
        end
    end
end